### PR TITLE
Bug: parameters not selected shown in results

### LINKED ISSUE #606: Bug: Parameters not selected shown in results if required for calculations
### Description
If you only want to see one parameter and so select it, but then that parameter requires other parameters for calculation (e.g `R2adj` requires `halflife` which requires `tmax`and `tlast`) then all parameters will appear in results.

### To reproduce
Deselect all parameters except for R2ADJ, see that there are more parameters shown.

### Expected behaviour
Filter final results so that only the parameters given in parameter selection are visible (can use TRUE intervals in `results$data$intervals` to filter rather than passing on parameter selection from a separate module)

### Definition of Done

- [ ] Results filtered for selected parameters
- [ ] ADPP and PP filtered for selected parameters
- [ ] Exports filtered for selected parameters

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #606 

## Description

If parameters are required for the calculation of otheres (eg in Depends col of metadata), or if they are required for rule sets, the parameters were shown in the results despite not being selected in parameter selection.
Now, the results are filtered based on parameter selection. They are filtered after being calculated to ensure that any params required for calculations or rule sets are available for processing.

## Definition of Done

- [x] Parameters filtered based on parameter selection
- [x] No additional parameters shown in results

## How to test

Run NCA with only one parameter eg RSQADJ, view difference between this branch and main. Check that rule sets are still correctly applied.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] Package version is incremented

### CODE REVIEW

File: inst/shiny/modules/tab_nca.R [hunk 1]
```diff
@@ -210,10 +210,23 @@ tab_nca_server <- function(id, adnca_data, grouping_vars) {
 
         log_success("NCA results calculated.")
 
-        # Apply standard CDISC names and return the object
-        res %>%
-          mutate(PPTESTCD = translate_terms(PPTESTCD, "PKNCA", "PPTESTCD"))
+        # Reshape intervals, filter for TRUE
+        requested_params <- res$data$intervals %>%
+          pivot_longer(
+            cols = where(is.logical),
```
Comment (Gero1999) [inline inst/shiny/modules/tab_nca.R:216]: issue: parameters can also be numeric/NA (not only TRUE/FALSE). So it is better if we can reshape a bit this to prevent future issues. Consider a strategy similar to the one done in `parameter_datasets.R`, which should work fine: 

```
      params_not_requested <- res_nca_req$data$intervals %>%
        select(any_of(setdiff(names(PKNCA::get.interval.cols()), c("start", "end")))) %>%
        # For all logical columns, mutate FALSE to NA
        mutate(across(where(is.logical), ~ ifelse(.x, TRUE, NA))) %>%
        # Only select column that are only NA
        select(where(~ all(is.na(.x)))) %>%
        names()
      res_nca_req$result <- res_nca_req$result %>%
        filter(!PPTESTCD %in% translate_terms(params_not_requested, "PKNCA", "PPTESTCD"))
```

**Review by Gero1999 — CHANGES_REQUESTED** [review]

**Review by m-kolomanski — APPROVED** [review]
LGTM

**Review by Gero1999 — CHANGES_REQUESTED** [review]
Hey @js3110 this might not work for ratio parameters when customized... If possible follow the strategy indicated in this [previous feedback](https://github.com/pharmaverse/aNCA/pull/646#discussion_r2352540464)
