### PR TITLE
Bug: units table multiple analyte display & results only working for all analytes with same units

### LINKED ISSUE #218: Bug: Units table for multiple analyte is duplicated
### Description
When running a multiple analyte study the table displayed to indicate the units is unnecessarily repeated, which can be confusing for the user.  

### To reproduce
Dummy_data_complex (multiple analytes) >> Map data >> NCA settings >> Units table

### Expected behaviour
- [ ] Units table should only have one row per parameter

### PR DESCRIPTION
**Pull request by Gero1999**
## Issue

Closes #218 

## Description

When running a multiple analyte study the table displayed to indicate the units is unnecessarily repeated, which can be confusing for the user.

## Definition of Done
- [x] Units table is not replicated per analyte when selecting both in the module message "Units Table"
- [x] Using different units per analyte will show up in results accordingly

## How to test
Map data > NCA setup > Select all analytes in input > Units Table button
Then play with it to see it works and does not crush easily. After that
Run NCA > Check results

How to test features not covered by unit tests.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [ ] Package version is incremented

## Notes to reviewer

Anything that the reviewer should know before tacking the pull request?

### CODE REVIEW

File: R/pivot_wider_pknca_results.R [hunk 1]
```diff
@@ -19,50 +19,59 @@
...
+  # Derive lambda.z.n.points & lambda.z.method
+  # ToDo: At some point this will be integrated in PKNCA and will need to be removed//modified
+  added_params <- NULL
+  if (all(c("lambda.z",
+            "lambda.z.n.points",
+            "lambda.z.time.first") %in% unique(myres$result$PPTESTCD))) {
+    added_params <- myres$result %>%
+      filter(PPTESTCD %in% c("lambda.z.n.points", "lambda.z.time.first", "lambda.z"),
+             type_interval == "main") %>%
+      select(unname(unlist(myres$data$conc$columns$groups)),
```
Comment (m-kolomanski) [inline R/pivot_wider_pknca_results.R:32]: nitpick: might be worth assigning this to a variable, since it is repeated a lot of times
```R
col_groups <- unname(unlist(myres$data$conc$columns$groups)
```
or something like this.

**Review by m-kolomanski — COMMENTED** [review]
The units table still seems duplicated for me:
Screenshot from 2025-02-26 10-15-37

File: inst/shiny/modules/units_table.R [hunk 2]
```diff
@@ -77,11 +77,22 @@ units_table_server <- function(id, mydata, res_nca = reactiveVal(NULL)) {
...
+    # Create a function to provide a clean display of the modal units table
+    clean_display_units_table <- function(data, selected_analytes) {
+      data %>%
+        mutate(`Conversion Factor` = signif(`Conversion Factor`, 3)) %>%
+        filter(`Analytes` %in% selected_analytes) %>%
+        group_by(Parameter, `Default unit`, `Conversion Factor`, `Custom unit`) %>%
+        mutate(Analytes = paste(Analytes, collapse = ", ")) %>%
+        ungroup() %>%
+        unique()
+    }
```
Comment (m-kolomanski) [inline inst/shiny/modules/units_table.R:89]: issue: This function should be outside of the `moduleServer`. Since it is used only within this module, it could be within the same file, just have a `.` in the name to signify it is a local function. Or,  it could be moved to `functions/` folder.

**Review by m-kolomanski — CHANGES_REQUESTED** [review]
issue: Even if only one of the analytes is selected in the settings, the units table will still propose both. This might be a bit confusing.
[Screencast from 2025-02-27 08-19-39.webm](https://github.com/user-attachments/assets/f639fe34-141f-400a-8960-999378740609)

**Review by m-kolomanski — APPROVED** [review]
Thank you for the changes, looks good!

**Review by js3110 — APPROVED** [review]
LGTM!

File: R/pivot_wider_pknca_results.R [hunk 3]
```diff
@@ -19,57 +19,63 @@
...
+  # ToDo: At some point this will be integrated in PKNCA and will need to be removed//modified
+  conc_groups <- unname(unlist(myres$data$conc$columns$groups))
 
-  # Create duplicates for accurate lambda.z.ix calculation
   data_with_duplicates <- dose_profile_duplicates(
     myres$data$conc$data,
     c(unlist(unname(myres$data$conc$columns$groups)),
       "DOSNO")
   )
+  added_params <- NULL
```
Comment (js3110) [inline R/pivot_wider_pknca_results.R:32]: @Gero1999 what are these changes for? how are they related to units?
and lambda.z.ix is incorrect in this branch, but correct in main so maybe its better to restore the changes, except the ones related to units. 
as lambda.z.ix was fixed in a different issue that has since been merged.

Comment (js3110) [reply R/pivot_wider_pknca_results.R:32]: actually nvm i checked main and the issues are also there. I will create a separate issue to address this!

**Review by js3110 — APPROVED** [review]
