### PR TITLE
Bug: Disallow user to check NCA / Outputs tabs without mapping data

### LINKED ISSUE #143: Bug: Disallow user to check NCA / Outputs tabs without mapping data
### Description
When user has not mapped the data (define column names and accepted) it should not be able to go through other tabs (NCA or Outputs) as it can be confusing for them to see errror messages afterwards. Instead, those tabs should remain disable and perhpaps even show a notification

### To reproduce
Intiiate the app and click NCA or Outputs tab. In the second one you won't find results but instead just error messages.

### Expected behaviour
Disability to go to Ouptuts or NCA without mapping.
Notification with instructions on what to do (mapping the data)

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #143 

## Description

When user has not mapped the data (define column names and accepted) it should not be able to go through other tabs (NCA or Outputs) as it can be confusing for them to see errror messages afterwards. Instead, those tabs should remain disable and perhpaps even show a notification

## Definition of Done

- [x] User cannot use other tabs until data is mapped
- [x] Once data is mapped, other tabs are enables

### CODE REVIEW

File: inst/shiny/ui.R [hunk 1]
```diff
@@ -221,12 +222,12 @@ fluidPage(
...
 
     # VISUALISATION ----
-    nav_panel("Visualisation",
+    nav_panel("Visualisation", value = "visualisation",
       fluid = TRUE,
       tab_visuals_ui("visuals")
     ),
     # New TLG tab
-    nav_panel("TLG",
+    nav_panel("TLG", value = "tlgs",
```
Comment (m-kolomanski) [inline inst/shiny/ui.R:230]: nitpick: Since every other element (title, module name, module id) refers to this tab as `tlg` and not `tlgs`, I would keep that consistent and give it the same value.

File: inst/shiny/modules/column_mapping.R [hunk 2]
```diff
@@ -277,6 +277,11 @@ column_mapping_server <- function(id, data, manual_units, on_submit) {
     observeEvent(input$submit_columns, {
       Sys.sleep(1) # Make this artificially slow to show the loading spinner
 
+      # Enable other tabs
+      shinyjs::enable(selector = "#page li a[data-value=nca]")
+      shinyjs::enable(selector = "#page li a[data-value=visualisation]")
+      shinyjs::enable(selector = "#page li a[data-value=tlgs]")
```
Comment (m-kolomanski) [inline inst/shiny/modules/column_mapping.R:283]: suggestion: In repetitive calls like this you can utilize some functional programming with `purrr`:
```suggestion
  purrr::walk(c("nca", "visualisation", "tlgs"), \(tab) {
    shinyjs::disable(selector = paste0("#page li a[data-value=", tab, "]"))
  })
```
but in this case, considering not much code repetition, it is absolutely fine.

**Review by m-kolomanski — APPROVED** [review]
Looks good to me, thank you! I have added two nitpicks/suggestions to consider, but the change is fine as is.

**Review by Gero1999 — CHANGES_REQUESTED** [review]
Hey good job! I think this solution is clean and simple 👌🏽 

In terms of feature I will also add a nitpick request! Could you also include a message in `Review Data` that until the dataframe is uploaded says something like: "Please, remember to submit your variables mapping in `Mapping and Filters`"

**Review by Gero1999 — APPROVED** [review]
lgtm good job!
