### PR TITLE
Bug: Boxplot crash when switching to violin plot

### LINKED ISSUE #683: Bug: Boxplot crashes when you switch to violin plot
### Description
When running through dummy dataset with default settings, and click on parameter plots, boxplot crashes when you click the violin plot toggle.

### To reproduce
When running through dummy dataset with default settings, and click on parameter plots, boxplot crashes when you click the violin plot toggle.

```
Warning: Error in order: argument 1 is not a vector
  109: <Anonymous>
  108: stop
  107: boxplot
  106: renderPlotly [modules/tab_nca/parameter_plots.R#151]
```

### Expected behaviour
Boxplots should not crash.
#396 can be included to update the options

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #683 

## Description

Boxplots were crashing when switching to violin plot, due to the ggplotly conversion not being compatible with the violinplot aesthetics. To fix, the aes are not inherited in violin plot and are instead assigned directly there.

## Definition of Done

- [x] Box and violin plots working

## How to test

Go to boxplots and switch between box and violin for various parameters.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] App or package changes are reflected in NEWS
- [x] Package version is incremented

## Notes to reviewer

Note: I merged branch from #695 into this one so ideally the other PR should merge first.

### CODE REVIEW

File: R/flexible_violinboxplot.R [hunk 1]
```diff
@@ -167,3 +181,41 @@ create_filter_expr <- function(boxplotdata, varvalstofilter) {
...
+        } else {
+          box_data$tooltip_text <- NA_character_
+        }
+      }
+    } else {
+      box_data$tooltip_text <- NA_character_
+    }
+  } else {
+    box_data$tooltip_text <- character(0)
+  }
```
Comment (m-kolomanski) [inline R/flexible_violinboxplot.R]: suggestion: This is basically the same outcome. I would suggest assigning `NA` at the top of the function, and then overwriting it accordingly depending on the checks.

File: R/flexible_violinboxplot.R [hunk 2]
```diff
@@ -167,3 +181,41 @@ create_filter_expr <- function(boxplotdata, varvalstofilter) {
...
+    if (!is.null(tooltip_vars)) {
+      if (!is.null(labels_df)) {
+        # Use the shared helper function if available and labels provided
+        box_data$tooltip_text <- generate_tooltip_text(box_data, labels_df, tooltip_vars, "ADNCA")
+      } else {
+        # Fallback: Create simple "Var: Value" string
+        valid_vars <- intersect(tooltip_vars, names(box_data))
+        if (length(valid_vars) > 0) {
+          parts <- lapply(valid_vars, function(v) paste0(v, ": ", box_data[[v]]))
+          box_data$tooltip_text <- do.call(paste, c(parts, sep = "<br>"))
```
Comment (m-kolomanski) [inline R/flexible_violinboxplot.R]: issue: This should be the same:
```suggestion
          box_data$tooltip_text <- paste(parts, collapse = "<br>")
```

Is there a specific reason for using `do.call` that I am missing?
