### PR TITLE
Bug: nca widget run every change

### LINKED ISSUE #275: Bug: Every change in NCA setup runs the NCA widget
### Description
The loading widget intended for when the user pressess run NCA is happening every time the user makes changes in the NCA setup. It seems that calculations are happening constantly instead of once. This maybe is an issue with the recent merge #233 

### To reproduce
Map data > NCA setup > Do changes one by one > Check bot-left the loading widget appearing

### Expected behaviour
- [x] Calculations for the lambda.z in the plots should optimally be done once after mapping and once per NCA-run.
- [x] Loading widget should not appear unless there is a NCA-run

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #275 

## Description
Loading widget was loading every time user updates setup options. This was due to the NCA being rerun every time, in order to update the slopes.

To make the process more organised and clean, I have split the updating of PKNCAdata object into two: one for slopes and one for the main NCA. For this, I created the function `PKNCA_update_data_object`
The slopes data is that used to run the NCA for the slope plots, and the other data is used for the main NCA. They are set up in the same way to ensure consisitency between slope plots and results, but are separated to prevent delays in data loading and lags in the interval setup.

## Definition of Done

- [x] Calculations of lambda.z in plots are less frequent
- [x] Loading widget does not appear unless Run NCA is clicked

## How to test

Load data and play around with adjusting settings, viewing slopes and intervals etc.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] Package version is incremented

## Notes to reviewer

Things that I think still need modifications, just maybe in separate issues:
- parameter input selection needs to change, as with pickerInput the box closes after every modification, so you can't select multiple in one go
- intervals table could be changed so it displays more simple information (not sure that parameters are needed in the table)

### CODE REVIEW

File: R/PKNCA.R [hunk 1]
```diff
@@ -143,6 +143,100 @@ PKNCA_create_data_object <- function(adnca_data) { # nolint: object_name_linter
...
+#' @param selected_dosno User selected dose numbers
+#' @param selected_pcspec User selected specimen
+#' @param params A list of parameters for NCA calculation
+#' @param should_impute_c0 Logical indicating if start values should be imputed
+#'
+#' @returns A fully configured `PKNCAdata` object.
+#'
+#' @importFrom dplyr filter mutate select across all_of
+#' @importFrom tidyr crossing
+#' @importFrom shiny reactive req showNotification
```
Comment (m-kolomanski) [inline R/PKNCA.R:172]: issue: Logic functions should not use any functions from `shiny`, especially to do with reactive logic or display. `reactive` and `showNotification` are not used in the function anyway?

File: R/PKNCA.R [hunk 2]
```diff
@@ -143,6 +143,100 @@ PKNCA_create_data_object <- function(adnca_data) { # nolint: object_name_linter
...
+  method,
+  selected_analytes,
+  selected_dosno,
+  selected_pcspec,
+  params,
+  should_impute_c0 = TRUE
+) {
+
+  req(adnca_data, method, selected_analytes,
+      selected_dosno, selected_pcspec)
```
Comment (m-kolomanski) [inline R/PKNCA.R:187]: issue: `req` call should be in the observer / reactive that calls the function.

If you wish to validate if the values for arguments are correct, use things like `stopifnot(!"PKNCAdata %in% class(adnca_data))` or simple `if` statements etc.

File: R/PKNCA.R [hunk 3]
```diff
@@ -143,6 +143,100 @@ PKNCA_create_data_object <- function(adnca_data) { # nolint: object_name_linter
...
+#' @param method NCA calculation method selection
+#' @param selected_analytes User selected analytes
+#' @param selected_dosno User selected dose numbers
+#' @param selected_pcspec User selected specimen
+#' @param params A list of parameters for NCA calculation
+#' @param should_impute_c0 Logical indicating if start values should be imputed
+#'
+#' @returns A fully configured `PKNCAdata` object.
+#'
+#' @importFrom dplyr filter mutate select across all_of
```
Comment (m-kolomanski) [inline R/PKNCA.R:170]: nitpick: `across` and `all_of` are not used in the function

File: R/PKNCA.R [hunk 4]
```diff
@@ -143,6 +143,100 @@ PKNCA_create_data_object <- function(adnca_data) { # nolint: object_name_linter
...
+#'
+#' This function updates a previously prepared `PKNCAdata` object
+#' based on user selections for method, analyte, dose, specimen, and parameters.
+#' @details
+#' Step 1: Update units in the `PKNCAdata` object
+#' ensuring unique analytes have their unique units
+#' Step 2: Set `PKNCAoptions` for NCA calculation
+#' Step 3: Format intervals using `format_pkncadata_intervals()`
+#' Step 4: Apply filtering based on user selections
+#' Step 5: Impute start values if requested
```
Comment (m-kolomanski) [inline R/PKNCA.R:158]: nitpick: In the documentation, this will render as a single line. To give it a nice separation (so it forms a list) add empty lines inbetween each point or use 

```suggestion
#' Step 1: Update units in the `PKNCAdata` object
#' ensuring unique analytes have their unique units
#'
#' Step 2: Set `PKNCAoptions` for NCA calculation
#'
#' Step 3: Format intervals using `format_pkncadata_intervals()`
#'
#' Step 4: Apply filtering based on user selections
#'
#' Step 5: Impute start values if requested
```

or you can plant `*` before each item to create a list, or maybe use `\enumerate{}`.

**Review by m-kolomanski — CHANGES_REQUESTED** [review]
Hey, looks very nice in general. I have some very minor issues that I cannot pass, I will approve as soon as those are dealt with.

**Review by Gero1999 — CHANGES_REQUESTED** [review]
Hey good job! For now I noticed this errors, need to keep checking:

- [ ] Method choices in NCA setup are repeated 
- [ ] Problem with Next and Before button in Slope Selection section 

The second one maybe is from main. I will keep reviewing after lunch! :)

**Comment by js3110** [comment]
> * [ ]  Method choices in NCA setup are repeated
> * [ ]  Problem with Next and Before button in Slope Selection section

both of these are from main :)

**Comment by js3110** [comment]
@m-kolomanski do you have any idea why my checks are failing? I merged with main so not sure why....

**Comment by m-kolomanski** [comment]
@js3110 From what I can see, your merge to `main` was ~7 hours ago and less than an hour I have merged a PR that changed the checks failing from _warning_ to _note_, so I am afraid you will have to merge again, sorry!

**Comment by Gero1999** [comment]
@js3110  not working for me after mappinng

```
Warning: Error in get.interval.cols: could not find function "get.interval.cols"
  142: eventReactiveValueFunc [modules/tab_nca/slope_selector.R#154]
   98: lambdas_res
   91: <reactive:profiles_per_patient> [modules/tab_nca/slope_selector.R#167]
   75: profiles_per_patient
   68: <reactive:plot_data> [modules/tab_nca/slope_selector.R#292]
   52: r
   46: observe
   45: <observer>
    2: shiny::runApp
    1: aNCA::run_app [C:/Users/rodrig60/Documents/aNCA/R/run_app.R#6]
```

**Review by Gero1999 — CHANGES_REQUESTED** [review]
@js3110 not working for me after doing the column mapping

```
Warning: Error in get.interval.cols: could not find function "get.interval.cols"
  142: eventReactiveValueFunc [modules/tab_nca/slope_selector.R#154]
   98: lambdas_res
   91: <reactive:profiles_per_patient> [modules/tab_nca/slope_selector.R#167]
   75: profiles_per_patient
   68: <reactive:plot_data> [modules/tab_nca/slope_selector.R#292]
   52: r
   46: observe
   45: <observer>
    2: shiny::runApp
    1: aNCA::run_app [C:/Users/rodrig60/Documents/aNCA/R/run_app.R#6]
   ```

**Comment by js3110** [comment]
@Gero1999 was a namespacing issue, fixed now!

**Comment by js3110** [comment]
@Gero1999 tests are updated!

**Review by Gero1999 — APPROVED** [review]
lgtm!
