### PR TITLE
fix: move required Shiny app packages from Suggests to Imports

### LINKED ISSUE #1207: Bug: `aNCA::run_app()` requires packages in the `Suggests` list
### Description

Some of the Suggests packages appear to be required for using aNCA

### To reproduce

1. Install aNCA (`install.packages("aNCA")`) in a system without other packages installed
2. Run `aNCA::run_app()`

```
Error in check_app_dependencies() : 
  Some packages required for Shiny application are missing. You can install them by running `install.packages(c('logger', 'reactable.extras', 'shinyjqui'))`
```

### Expected behaviour

Basic package installation should allow `aNCA::run_app()` to work without additional steps. It seems like these packages are required but not installed by default. Please either consider switching them to a Imports or finding a way that the package can work without the listed packages.

### PR DESCRIPTION
**Pull request by Gero1999**
## Issue

Closes #1207

## Description

`run_app()` fails on a clean install because several packages required by the Shiny app are listed in `Suggests` instead of `Imports`. Users must manually install `logger`, `reactable.extras`, `shinyjqui`, and others before the app can start.

This PR reclassifies packages based on a full audit of usage across `R/` and `inst/shiny/`:

**Moved from Suggests → Imports** (required at app startup, no fallback possible):
- `bslib`, `htmltools`, `htmlwidgets`, `logger`
- `reactable`, `reactable.extras`
- `shiny`, `shinycssloaders`, `shinyjs`, `shinyjqui`, `shinyWidgets`
- `zip`

**Removed entirely:**
- `stringi` — only used for random string generation (2 calls). Replaced with base R `paste0(sample(c(letters, 0:9), 5, replace = TRUE), collapse = "")`.

**Kept in Suggests** (properly guarded with `requireNamespace()` or dev/test-only):
- File readers: `arrow`, `haven`, `readxl` — guarded in `R/readers.R`
- Export formats: `officer`, `flextable` — guarded in `inst/shiny/functions/zip-utils.R`
- TLG: `rlistings`, `ggh4x` — guarded at point-of-use
- Reporting: `quarto` — guarded in `R/quarto-utils.R`
- Dev/test: `covr`, `DT`, `jsonlite`, `knitr`, `lintr`, `markdown`, `mockery`, `nestcolor`, `pak`, `rmarkdown`, `sass`, `scales`, `shinytest2`, `testthat`, `vdiffr`, `withr`

**Other changes:**
- `check_app_dependencies()` now reads the `Imports` field from `DESCRIPTION` automatically instead of maintaining a hardcoded list.
- Removed `require(stringi)` from `inst/shiny/app.R`.
- Added `R/imports-shiny.R` with `@importFrom` directives for packages only used in `inst/shiny/` (required by `R CMD check`).
- Added `tryCatch` guard to `sessionInfo()` rendering in the About tab.
- Added `data-raw/test_suggests_hidden.R` for manual dependency testing.
- Added dependency test step to the PR checklist template.

## Definition of Done

- `install.packages("aNCA")` installs all packages needed for `run_app()` to work without additional steps.
- Optional features (SAS import, PowerPoint export, etc.) degrade gracefully with informative messages when their packages are missing.

## How to test

Use the manual test script in a fresh R session:

```r
source("data-raw/test_suggests_hidden.R")
```

This hides all `Suggests` packages, loads the package, and launches `run_app()`. Verify:

1. The app starts without errors.
2. Core workflow works: upload data → map variables → run NCA → export ZIP.
3. Optional features (SAS import, PowerPoint export, listings) show graceful messages instead of crashing.

After stopping the app, restore packages:

```r
restore_packages()
```

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] App or package changes are reflected in NEWS
- [x] Package version is incremented
- [x] R script works with the new implementation (if applicable)
- [x] Settings upload works with the new implementation (if applicable)
- [x] If any `.scss` change was done, run `data-raw/compile_css.R`
- [x] If a package dependency was added/changed, run `data-raw/test_suggests_hidden.R`

## Notes to reviewer

This is a dependency classification fix, not a behavior change. The app should function identically — the only difference is that `install.packages("aNCA")` now pulls in everything needed for `run_app()`.

The `stringi` replacement uses base R's `sample()` which is sufficient for generating unique module IDs.

Version bump and NEWS entry still needed before merge.

### CODE REVIEW

**Review by js3110 — COMMENTED** [review]
Hey, looks good. I am getting two additional warning messages when I run with the hidden pacakges:

```
Warning in FUN(X[[i]], ...) :
  DESCRIPTION file of package 'shinytest2' is missing or broken

Warning message:
In read.dcf(file.path(p, "DESCRIPTION"), c("Package", "Version")) :
  cannot open compressed file '/AppData/Local/R/win-library/4.4/knitr/DESCRIPTION', probable reason 'No such file or directory'
```

File: data-raw/test_suggests_hidden.R [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+# --- Restore function (call after stopping the app) ---
+restore_packages <- function() {
+  for (pkg in hidden) {
+    to <- file.path(lib, pkg)
+    from <- paste0(to, "_HIDDEN")
+    if (dir.exists(from)) file.rename(from, to)
+  }
+  cat("Restored:", paste(hidden, collapse = ", "), "\n")
+}
```
Comment (js3110) [inline data-raw/test_suggests_hidden.R:49]:
```suggestion
}

# Restore packages after stopping app
restore_packages()
```

**Comment by Gero1999** [comment]
> Hey, looks good. I am getting two additional warning messages when I run with the hidden pacakges:
> 
> ```
> Warning in FUN(X[[i]], ...) :
>   DESCRIPTION file of package 'shinytest2' is missing or broken

This type of messages are for now expected, should not be a problem in the future

> Warning message:
> In read.dcf(file.path(p, "DESCRIPTION"), c("Package", "Version")) :
>   cannot open compressed file '/AppData/Local/R/win-library/4.4/knitr/DESCRIPTION', probable reason 'No such file or directory'

@js3110 This one on the other hand I am not completely clear why it happens to you

**Comment by js3110** [comment]
ok @Gero1999 , idk either but everyting still works anyway, so I guess the warning messages can be ignored

**Review by js3110 — APPROVED** [review]
LGTM :)

**Comment by Gero1999** [comment]
@billdenney feel free to check this PR if you have time

**Comment by Shaakon35** [comment]
@Gero1999 It does not work for me, I followed the how to test instructions and downloaded the zip file with all, but it didn't work:
image

This bug of of downloading a htm file is annoying, we should fix this globally by a try catch...

**Comment by Gero1999** [comment]
@Shaakon35  Some exportable objects (PPT, session_info) are indeed coming from `Suggested` packages so they have to be addressed within the ZIP. Hopefully now is fixed

the session_info.txt will still appear for the user, but it will have the error message that indicates that could not be done. I don't want to change it per ce because other branches are already modifying the way it behaves (as it might stop using the `logger` package)

**Review by bachapman — APPROVED** [review]
Works well for me!

**Review by Shaakon35 — APPROVED** [review]
