### PR TITLE
Bug/manual slope selection plot does not update if point is before current slope

### LINKED ISSUE #121: Bug: manual slope selection plot does not update if selected point is before current slope
### Description
When a manual slope selection is added, the plot only updates if the point selected is > time than the previous selection, otherwise it doesn't update visually. In the NCA results and in the table everything is fine, it is just the visuals of the plot.

### To reproduce
Run NCA -> Slope selector -> select a point that is before the current slope (black) and then click the end point. The black point selected does not turn green.

### Expected behaviour
The black point selected should turn green and be included in the line of best fit

### PR DESCRIPTION
**Pull request by m-kolomanski**
## Issue

Closes #121 

## Description

Fixes an issue where points located before the automatically selected slope.

## Definition of Done

All points on the selected slope show as green on the plot.

## How to test

Run the app, map the data and go into NCA -> Slope selector. You will notice that the first couple of points on the plot are black - those are not currently selected. The green points will denote the automatic slope selection. Try adding a custom selection, either by clicking on the plot or via adding a selection in the table (you can keep it default and just adjust range), making sure that the selection starts at point 1. On `main` branch, the plot will not update - the first points will remain black. On this branch the selected range should correctly turn green.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] Package version is incremented

## Notes to reviewer
The changes introduced in this PR require the development version of `PKNCA` package. You can install it by running:
```R
install.packages("remotes")
remotes::install_github("billdenney/pknca")
```

Since we are pulling the package directly from github as opposed to CRAN, `R CMD check` in our CI will fail. This has been discussed and acknowledged, I have created a related issue #346 on the board. As soon as the new version of PKNCA package is released on CRAN, we should update our `DESCRIPTION` file so it does not rely on the github repo.

### CODE REVIEW

File: inst/shiny/modules/tab_nca/slope_selector.R [hunk 1]
```diff
@@ -142,36 +142,51 @@ slope_selector_server <- function(
...
+      shiny::debounce(750)
+
+    #' Plot data is a local reactive copy of full data. The purpose is to display data that
+    #' is already adjusted with the applied rules, so that the user can verify added selections
+    #' and exclusions before applying them to the actual dataset.
+    plot_data <- reactive({
+      req(pknca_data(), manual_slopes(), profiles_per_patient())
+      filter_slopes(pknca_data(), manual_slopes(), profiles_per_patient(), slopes_groups())
+    }) %>%
+      shiny::debounce(750)
```
Comment (js3110) [inline inst/shiny/modules/tab_nca/slope_selector.R:161]: question: is this intentionally repeated ?

Comment (m-kolomanski) [reply inst/shiny/modules/tab_nca/slope_selector.R:161]: No, must be an artifact from rebasing the branch to main, good spot!

File: tests/testthat/test-create_start_impute.R [hunk 2]
```diff
@@ -31,7 +31,12 @@ intervals_data <- data.frame(
 conc_obj <- PKNCA::PKNCAconc(conc_data, conc ~ time | USUBJID + DOSNO / param)
 dose_obj <- PKNCA::PKNCAdose(dose_data, dose ~ time | USUBJID + DOSNO,
                              duration = "duration", route = "route")
-mydata <- PKNCA::PKNCAdata(conc_obj, dose_obj, intervals = intervals_data)
+mydata <- PKNCA::PKNCAdata(
+  conc_obj,
+  dose_obj,
+  intervals = intervals_data,
+  options = list(keep_interval_cols = c("auc.obs", "auc.pred"))
```
Comment (js3110) [inline tests/testthat/test-create_start_impute.R:38]: I've just noticed while working on something else that this doesn't need to be added here, its because in intervels_data thats created, auch.obs and auc.pred are created even though these aren't real pknca parameters.

just need to update intervals_data instead:
```
intervals_data <- data.frame(
  start = c(0, 0, 3, 0, 3, 0, 0, 0),
  end =   c(3, 3, 6, 3, 6, 3, 3, 3),
  USUBJID =  c(1, rep(2, 2), rep(3, 2), 4, 5, 6),
  DOSNO = c(1, 1, 2, 1, 2, 1, 1, 1),  # Include second dose profile for USUBJID 6
  tmax = TRUE,
  auclast = TRUE,
  aucinf.pred = TRUE
)
```

**Review by rabiibouhestine — APPROVED** [review]
LGTM

**Comment by js3110** [comment]
hi, I am getting the error 
```
Error in module: object 'profiles_per_subject' not found
  55: module [modules/tab_nca/slope_selector.R#340]
```

Probably linked to the fact that in #334 patient was renamed to subject.

**Comment by js3110** [comment]
thanks @m-kolomanski ! On my end, I think it looks good, but I would prefer for @Gero1999 to review this since I am the one who worked on the code, and it would be good to get someone else to review the PKNCA aspect!

**Comment by m-kolomanski** [comment]
Currently blocked and waiting on changes in #374 to be merged.

**Review by js3110 — APPROVED** [review]
Looks good to me ! Thanks :)
