### PR TITLE
Bug : Bioavailability not working

### LINKED ISSUE #705: Bug: Bioavailability calculations not working
### Description
Bioavailability calculations are not working, instead duplicate records of subjects are in results but with empty columns.

### To reproduce
Test using adnca_sm_dataset in testthat folder, include FABLST paramter, see results.

### Expected behaviour
Bioavailability should be calculated.

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #705 

## Description

Bioavailability calculations were not working due to an uncaught bug after updating PKNCADose object to remove PCSPEC. Therefore grouping of dose info was not correct and the bioavailability calculations were failing. Fixed now by updating grouping.

## Definition of Done

- [x] Bioavailability calculated for subjects correctly

## How to test

Use dummy_adnca_sm.csv in testthat folder, and select bioavailability parameters. Check that the results look correct and are in the correct rows.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] Package version is incremented

### CODE REVIEW

File: R/bioavailability.R [hunk 1]
```diff
@@ -77,14 +78,17 @@ pknca_calculate_f <- function(res_nca, f_aucs) {
...
+      route_names = !!sym(route_col)
+    ) %>%
     # Pivot and calculate by group mean AUC and dose values
     rename(
       aucs = PPORRES,
       dose = any_of(dose_col)
     ) %>%
     pivot_wider(
-      names_from = any_of(route_col),
+      names_from = route_names,
```
Comment (Gero1999) [inline R/bioavailability.R]: suggestion: consider refactoring:

```suggestion
# Pivot and calculate by group mean AUC and dose values
rename(
aucs = PPORRES,
dose = any_of(dose_col),
route = any_of(route_col)
) %>%
pivot_wider(
      names_from = route,
```

**Review by Gero1999 — APPROVED** [review]
LGTM! just a refactoring suggestion, but feel free to merge
