### PR TITLE
Bug: AUC start 0 (which also needs Feature: C0 imputation)

### LINKED ISSUE #2: Feature: Impute initial concentrations for each subject at time zero (C0)
**Issue description**
Sample records are not taken for obvious reasons exactly when the dose is provided. It is very standard to impute these values for each subject using different strategies depending on the route of administration, the time-close collected samples and the observed kinetics of the drug. 

**Notes**
1) If a drug is not IV bolus, C0=0. 
 2) If is IV bolus and the concentration decline is monoexponential it will be extrapolated using a linear regression
 3) If there are postdoses in the first five minutes, the closes to t0 can be used for C0.

### PR DESCRIPTION
**Pull request by Gero1999**
## Issue
Closes #2 #60

## Description
After running NCA, AUC calculations always consider the discrete start (start at where first concentration sample was collected). This can indeed alter slightly the real values of the AUC. This is a consequence of 2 problems:

1) Doses times are being considered at the first measure, instead of at the real dose time
2) No imputed measure at dose time is consdiered

Change description.

## Definition of Done
C0 imputation option for the user specified in Setup > Data Selection

## How to test
- [x] At "NCA">"NCA Results", when C0 is imputed it is expected that start=AFRLT-ARRLT (being AFRLT-ARRLT= 0 in DOSNO=1)
- [x] At "NCA">"NCA Results", when C0 is not imputed it is expected that start={time of 1st observation} 
- [x] AUC values  (auclast, aucinf...) from start=AFRLT-ARRLT are calculated when C0 is imputed
- [x] All variables that should only be based on observed data (cmax, tmax...) are not considering C0 imputations
- [x] Test that PKNCA also deals well with predoses as duplicates for the NCA
- [x] Check slope selector plots and NCA results remain well after running NCA
- [x] Check if in general C0 imputation logic works well (NCA experts): 
if `C0 exists` ~ `C0=C0`
if `DOSNO=1 & IV bolus (ADOSEDUR=0, ROUTE=intravascular)` ~ `C0=0`
if `DOSNO>1 & not IV bolus` ~ `C0=predose`
if `IV bolus and monoexponential data` ~ `logslope`
if `IV bolus and not monoexponential data` ~ `C0=C1`

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented

## Notes to reviewer

Anything that the reviewer should know before tacking the pull request?

### CODE REVIEW

**Review by js3110 — CHANGES_REQUESTED** [review]
Nice work! Some requests:

Fixes:
- [ ] App crashes if AUC rule sets are selected
- [ ] Slope selector not working- i tested an exclusion and the app crashed. Haven't tried selections.
- [ ] Data table in Data selection tab is not sorted- needs to be sorted by USUBJID for better visualisation.

Enhancements:

- It would be good if the user can see an updated data table after the imputations, so they know what the data being used looks like. If this is too complex then maybe you can add an explanation of what the imputation is doing. But it would be good if they can see what data is being created.
- Some clarification/relabelling is required in terms of what the imputation does. 'C0 missing' is not always accurate, for example if the predose value is present in the data set but ATime is <0, it gets excluded, but its not technically missing. Some more clarification on this would be good for the user so they know that imputation is also for predose samples.
- Predose samples/ duplicates are not being included. Need to figure out a way to ensure they are- by creating duplicates manually or making sure PKNCA includes them.

**Review by m-kolomanski — CHANGES_REQUESTED** [review]
Hey,

Are the diffs displayed by github accurate? Seems like a lengthy change, are there any artifacts/errors that happened due to merge (it did happen to me on occasions)? If the diffs are inaccurate, please point out the actual changes and disregard the below.

I do not have the time to do a detailed review (it is quite a lengthy change), but after a quick look there is some general things I want to point out:

1. Please do not any files that solely generate UI to the `/R` folder - this is a folder for our logic. File `partial_auc_input` belongs in the `inst/shiny` folder, either in `/modules` (if there is any server logic attached, here it isnt, but might be added) or folder like `functions`. We can also create a new folder for UI elements, called `ui` or `elements` or `widgets` or whatever you find suitable.
2. If you are creating new files or adding new functions in the `/R` folder, please make sure that this logic is testable and do take some effort to write at least basic unit tests. Adding tests back to existing logic is tough and time consuming, so we should at least make sure that our testing suite keeps up with any new features or major changes to the old ones.
3.

**Comment by Gero1999** [comment]
> Hey,
> 
> Are the diffs displayed by github accurate? Seems like a lengthy change, are there any artifacts/errors that happened due to merge (it did happen to me on occasions)? If the diffs are inaccurate, please point out the actual changes and disregard the below.
> 
> I do not have the time to do a detailed review (it is quite a lengthy change), but after a quick look there is some general things I want to point out:
> 
> 1. Please do not any files that solely generate UI to the `/R` folder - this is a folder for our logic. File `partial_auc_input` belongs in the `inst/shiny` folder, either in `/modules` (if there is any server logic attached, here it isnt, but might be added) or folder like `functions`. We can also create a new folder for UI elements, called `ui` or `elements` or `widgets` or whatever you find suitable.
> 2. If you are creating new files or adding new functions in the `/R` folder, please make sure that this logic is testable and do take some effort to write at least basic unit tests. Adding tests back to existing logic is tough and time consuming, so we should at least make sure that our testing suite keeps up with any new features or major changes to the old ones.

Hello and happy new year @m-kolomanski !

You are right, this is a very lengthy change but I re checked and everything was intentional. Most of them are new created manuals for each function. As requested I also:

1. Deleted the extra UI function from `\R`
2. Added tests for all functions called in ``format_data,R`, `create_start_impute` and `PKNCA_impute_method_additions`

Don't hesitate to let me know if there is anything else I can do or if there are other concerns that I can address! I also asked @js3110 for re-review to make sure all looks as expected.

**Review by js3110 — APPROVED** [review]
LGTM

Need to create a new issue for the auc calculation to avoid using cmax automatically.

File: tests/testthat/test-format_data.R [hunk 1]
```diff
@@ -0,0 +1,326 @@
...
+  # Test if df_conc can be used with PKNCAconc by testing its output
+  expect_s3_class(
+    PKNCAconc(
+      df_conc,
+      formula = AVAL ~ TIME | STUDYID + PCSPEC + DRUG + USUBJID / ANALYTE,
+      exclude_half.life = "exclude_half.life",
+      time.nominal = "NFRLT"
+    ),
+    "PKNCAconc"
+  )
```
Comment (m-kolomanski) [inline tests/testthat/test-format_data.R:42]: issue: In this case, if `df_conc` was somehow wrong, we would expect an error from `PKNCAconc` function, so I would wrap that in `expect_no_error` to know exactly if a) an error occured or b) `PKNCAconc` returned something strange.
```suggestion
  expect_no_error({
    expect_s3_class(
      PKNCAconc(
        df_conc,
        formula = AVAL ~ TIME | STUDYID + PCSPEC + DRUG + USUBJID / ANALYTE,
        exclude_half.life = "exclude_half.life",
        time.nominal = "NFRLT"
      ),
      "PKNCAconc"
    )
  })
```

File: tests/testthat/test-format_data.R [hunk 2]
```diff
@@ -0,0 +1,326 @@
...
+
+  # Test if df_conc is correctly grouped and arranged
+  expect_equal(df_conc$TIME, df_conc$AFRLT)
+  expect_equal(df_conc %>%
+                 dplyr::arrange(USUBJID, DOSNO) %>%
+                 dplyr::pull(IX),
+               rep(1:5, 4))
+
+  # Test if df_conc can be used with PKNCAconc by testing its output
+  expect_s3_class(
```
Comment (m-kolomanski) [inline tests/testthat/test-format_data.R:83]: issue: As above, I would wrap that in `expect_no_error`.

File: tests/testthat/test-format_data.R [hunk 3]
```diff
@@ -0,0 +1,326 @@
...
+  expect_s3_class(df_dose, "data.frame")
+
+  # Test if df_dose has the correct columns
+  expect_true(all(c("STUDYID", "USUBJID", "PCSPEC",
+                    "DRUG", "ANALYTE", "AFRLT",
+                    "ARRLT", "AVAL", "conc_groups",
+                    "TIME", "IX", "ROUTE") %in% colnames(df_dose)))
+
+  # Test if df_dose can be used with PKNCAdose by testing its output
+  expect_s3_class(
```
Comment (m-kolomanski) [inline tests/testthat/test-format_data.R:173]: issue: As above, I would wrap that in `expect_no_error`.

File: tests/testthat/test-format_data.R [hunk 4]
```diff
@@ -0,0 +1,326 @@
...
+
+  # Test if myintervals has the correct columns
+  expect_true(all(c("start", "end", "STUDYID",
+                    "USUBJID", "type_interval") %in% colnames(myintervals)))
+
+  # Test if interval types are classified as "main"
+  expect_true(all(myintervals$type_interval == "main"))
+
+  # Test if myintervals can be used with PKNCAdata by testing its output
+  expect_s3_class(
```
Comment (m-kolomanski) [inline tests/testthat/test-format_data.R:312]: issue: As above, I would wrap that in `expect_no_error`.

File: R/format_data.R [hunk 5]
```diff
@@ -1,121 +1,162 @@
...
+  if (nrow(ADNCA) == 0) {
+    stop("Input dataframe is empty. Please provide a valid ADNCA dataframe.")
+  }
+
+  missing_columns <- setdiff(c(group_columns, time_column), colnames(ADNCA))
+  if (length(missing_columns) > 0) {
+    stop(paste("Missing required columns:", paste(missing_columns, collapse = ", ")))
+  }
+
+  data <- ADNCA %>%
```
Comment (m-kolomanski) [inline R/format_data.R:43]: issue: variable assignment not needed, can just return the pipe result
```suggestion
  ADNCA %>%
```

**Review by m-kolomanski — CHANGES_REQUESTED** [review]
Hey, happy new year to you too and thank you for all the hard work!

I have to request some changes and have some suggestions/nitpicks to consider. I know that some of my comments refer to lines that were not changed in this PR, but since we are working on those functions I think it would be beneficial to go back and improve the code, even if it is not directly related to the changes.

File: R/PKNCA_impute_method_additions.R [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+#' conc <- c(1, 2, 3, 4, 5)
+#' time <- c(0, 1, 2, 3, 4)
+#' start <- 0
+#' end <- 4
+#' PKNCA_impute_method_start_log(conc, time, start, end)
+
+PKNCA_impute_method_start_log <- function(conc, time, start, end, ..., options = list()) { # nolint
+
+  ret <- data.frame(conc = conc, time = time)
+  mask_start <- time %in% start
```
[the remark this answers is not in the document]
Comment (Gero1999) [reply R/PKNCA_impute_method_additions.R:23]: I think you are right. It is an unnecessary prevention of NAs in case `time` contains them, but it should not at this point

File: R/PKNCA_impute_method_additions.R [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+#' @examples
+#' conc <- c(1, 2, 3, 4, 5)
+#' time <- c(0, 1, 2, 3, 4)
+#' start <- 0
+#' end <- 4
+#' PKNCA_impute_method_start_log(conc, time, start, end)
+
+PKNCA_impute_method_start_log <- function(conc, time, start, end, ..., options = list()) { # nolint
+
+  ret <- data.frame(conc = conc, time = time)
```
[the remark this answers is not in the document]
Comment (Gero1999) [reply R/PKNCA_impute_method_additions.R:22]: I asked Bill because I actually followed his syntax from the other parallel functions. Apparently is from the word `return` (of the function). But I will change it to something more intuitive now

[the remark this answers is not in the document]
Comment (Gero1999) [reply R/PKNCA_impute_method_additions.R]: I put `d_conc_time`, hope that makes more sense!

File: R/create_start_impute.R [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+#' @import dplyr
+#' @importFrom rlang sym
+#' @importFrom PKNCA pk.calc.c0
+#' @export
+#'
+#' @examples
+#' \dontrun{
+#' mydata <- create_start_impute(mydata)
+#' }
+create_start_impute <- function(mydata) {
```
[the remark this answers is not in the document]
Comment (Gero1999) [reply R/create_start_impute.R:16]: I agree with this but I would prefer to change all `mydata` calls together at once to something we set. Maybe in an independent issue for renaming variables would be the best

**Comment by Gero1999** [comment]
Thanks for your reviews and feedback, I hope that now all looks fine! @js3110 @m-kolomanski

**Review by m-kolomanski — CHANGES_REQUESTED** [review]
Hey, looks much better, thank you for all the hard work! I still do have some feedback, most of it regards style and consistency rather thank quality of the code, but also there seems like some of my comments from the previous review were not addressed?

**Comment by js3110** [comment]
@Gero1999 it looks good and thank you for all the hard work on this! Unfortunately I have noticed a couple of things:

1. In the data selection, after you select analyte and dose number, the table shown does not represent the selections, as I can still see all the dose numbers. We want this table for the user to see exactly the data that will be used for NCA, so either we need to filter the dose number here, or move the dose number selectInput. I will let you decide.
2. For the dummy data, Doseno >3 does not work and the app crashes. I get the following error: Error in if: argument is of length zero. I double checked and I do not get this issue in main, so it is related to something in this branch. Also, for DOSNO = 2, USUBJID 11102 has empty cells for lambda z calculation, but no explanation why and because of this the slope selection crashes. This could be created as a separate bug issue to fix later or you can see if its something to fix now.

Let me know if you have any questions or want any support :)

File: R/PKNCA_impute_method_additions.R [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+#' start <- 0
+#' end <- 4
+#' PKNCA_impute_method_start_logslope(conc, time, start, end)
+
+PKNCA_impute_method_start_logslope <- function(conc, time, start, end, ..., options = list()) { # nolint
+
+  d_conc_time <- data.frame(conc = conc, time = time)
+  if (!any(time == start)) {
+    all_concs <- conc[time >= start  &  time <= end]
+    all_times <- time[time >= start  &  time <= end]
```
Comment (m-kolomanski) [inline R/PKNCA_impute_method_additions.R:29]: nitpick, style: 
```suggestion
    all_concs <- conc[time >= start & time <= end]
    all_times <- time[time >= start & time <= end]
```

File: R/create_start_impute.R [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+        is.first.dose & (!is.ivbolus | !is.analyte.drug) ~ "start_conc0",
+
+        # Posterior doses not IV bolus or analyte =! drug : Start concentration shifts to predose
+        !is.first.dose & (!is.ivbolus | !is.analyte.drug) ~ "start_predose",
+
+        # IV bolus with analyte = drug : Start concentration is log-backextrapolated (if possible)
+        is.ivbolus & is.analyte.drug & is.possible.c0.logslope ~ "start_logslope",
+
+        # IV bolus with analyte = drug and not possible logslope: Start concentration is 1st conc
+        is.ivbolus & is.analyte.drug ~ "start_c1"
```
Comment (m-kolomanski) [inline R/create_start_impute.R:93]: Nice, looks clean, thank you for additional comments with explanations!

File: inst/WORDLIST.txt
Comment (m-kolomanski) [inline inst/WORDLIST.txt:1]: issue(non-blocking): Please remove this file, it is redundant.

**Review by m-kolomanski — APPROVED** [review]
From my side, looks good! Thank you for all the hard work, this is a lengthy change, sure it was not easy!

I am approving, but before merge, please remove the `inst/WORDLIST.txt` file, as it is redundant - the spelllcheck only uses `WORDLIST` file.

**Review by js3110 — APPROVED** [review]
LGTM !!
