### PR TITLE
Fix intervals using impute when not needed

### LINKED ISSUE #290: Bug: intervals using impute when not needed
### Description

Some parameters are being calculated using the imputation, when they should be calculated only using the observed data and not imputed data.

### To reproduce
Run NCA on defualt settings
Subj 11106 DOSNO 1 has cmax included - halflife is calculated using imputation not observation

### Expected behaviour
tbc: need to define which parameters are allowed to be included or excluded from imputation calculations.

### PR DESCRIPTION
**Pull request by Gero1999**
## Issue

Closes #290 

## Description
Some parameters are being calculated using the imputation, when they should be calculated only using the observed data and not imputed data.

In specific I have assumed that the only parameters that we want to impute are AUC or AUC-derived. I used metadata information from PKNCA to know which parameters use AUC in their calculations. Feel free to give a check!

## Definition of Done
- [ ] non-AUC derived parameters are not imputed (half.life, cmax, tmax...)
- [ ] AUC derived parameters keep imputed when the checkbox is on

## How to test
To know if a parameter is imputed, the easiest is to check in `NCA > NCA setup` the table below. There is a column called `Impute` that is empty or NA when the interval row is not imputed. Check that those interval rows with imputation only include auc and auc derived columns as TRUE (auc.*, aumc.*, cl.*, kel.*)

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] Package version is incremented

## Notes to reviewer

Anything that the reviewer should know before tacking the pull request?

### CODE REVIEW

**Review by js3110 — CHANGES_REQUESTED** [review]
I am getting a crash and error messages:

`Warning: Error in filter: ℹ In argument: `grepl("auc", PKNCA) | grepl("aumc", PKNCA) | grepl("auc", Depends)`.
Caused by error:
! object 'Depends' not found
  2: shiny::runApp`

**Review by js3110 — APPROVED** [review]
LGTM ! thanks :)

File: R/PKNCA.R [hunk 1]
```diff
@@ -252,11 +252,23 @@ PKNCA_update_data_object <- function( # nolint: object_name_linter
   if (should_impute_c0) {
     data <- create_start_impute(data)
 
+    # Don't impute parameters that are not AUC dependent
+    params_auc_dep <- pknca_cdisc_terms %>%
+      filter(grepl("auc", PKNCA) | grepl("aumc", PKNCA) | grepl("auc", Depends)) %>%
```
Comment (m-kolomanski) [inline R/PKNCA.R:257]: suggestion:
```suggestion
      filter(grepl("auc|aumc", PKNCA) | grepl("auc", Depends)) %>%
```

File: R/PKNCA.R [hunk 2]
```diff
@@ -252,11 +252,23 @@ PKNCA_update_data_object <- function( # nolint: object_name_linter
...
+      pull(PKNCA)
+
+    params_not_to_impute <- pknca_cdisc_terms %>%
+      filter(!grepl("auc", PKNCA),
+             !grepl("aumc", PKNCA),
+             !grepl(paste0(params_auc_dep, collapse = "|"), Depends)) %>%
```
Comment (m-kolomanski) [inline R/PKNCA.R:263]: suggestion:
```suggestion
      filter(!grepl("auc|aumc", PKNCA),
             !grepl(paste0(params_auc_dep, collapse = "|"), Depends)) %>%
```

**Review by m-kolomanski — APPROVED** [review]
LGTM, two non-blocking suggestion added
