### PR TITLE
Bug/refactor/enhancement: Fix settings download/upload

### LINKED ISSUE #120: Bug: Settings upload does not update dose number
### Description
Settings upload does not update dose numbers in Settings Tab of NCA

### To reproduce
Upload settings
### Expected behaviour
Settings upload should find the dose number (profile) for the settings, and update the dose number widget in settings tab so that these dose numbers are selected in the selectInput

### PR DESCRIPTION
**Pull request by m-kolomanski**
## Issue

Closes #120, #418

## Description

This PR refactors the way settings are gathered and applied with further modularization of the workflow.

New major module is created in `modules/tab_nca/setup.R`. This module is responsible for gathering settings and slope selections and applying them to the data. It then returns the `processed_pknca_data` object that is used in the analysis.

This module uses several submodules in a `modules/tab_nca/setup/` folder:
- `settings.R` -> responsible for displaying and gathering basic settings.
- `slope_selector.R` and `manual_slopes_table.R` modules responsible for gathering manual slope selections/exclusions.
- `summary.R` responsible for displaying processed data.

Settings are gathered into more cohesive list and tables and returned in more controlled manner.

This PR also fixes settings download and upload. The `setup.R` module handles gathering relevant data and enables the user to download the settings file in `.Rds` file. This file can then be uploaded to the app to overwrite existing settings. Relevant sub-moduels take in `*_override()` reactives. Upon change in those, the current UI and returned settings will be overwritten by whatever user uploads.

## Definition of Done

- No app functionality has been broken by the changes.
- Settings are correctly applied to the PKNCAdata object and are reflected in results.
- Downloading existing settings works.
- Uploading settings file works and settings are correctly applied to the data.

## How to test

Go into the app, map the data, go to settings. Try downloading `.Rds` file with the settings. Try changing the settings: select/deselect params, flags, change flag thresholds, select different analytes, does, methods etc. Add slope selections/exclusions. Then try loading the settings file and check if all the settings went back to the same state as it was when the file was downloaded. Run the analysis and check if the settings are properly applied (e.g. check for existence of flags in the results).

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic is documented
- [x] Package version is incremented

## Notes to reviewer

Anything that the reviewer should know before tacking the pull request?

### CODE REVIEW

File: inst/shiny/modules/tab_nca/setup.R [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+    nav_panel(
+      "Settings",
+      fluidRow(
+        column(6,
+          fileInput(
+            ns("settings_upload"),
+            width = "100%",
+            label = "Upload settings",
+            buttonLabel = list(icon("folder"), "Browse"),
+            accept = c(".csv", ".xpt")
```
Comment (Gero1999) [inline inst/shiny/modules/tab_nca/setup.R:30]: issue: put the expected format
```suggestion
            accept = ".rds"
```

File: inst/shiny/modules/tab_nca/setup.R [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+      "slope_selector",
+      slopes_pknca_data,
+      manual_slopes_override
+    )
+
+    summary_server("nca_setup_summary", processed_pknca_data)
+
+    # Handle downloading and uploading settings
+    output$settings_download <- downloadHandler(
+      filename = "aNCA_app_setup.Rds",
```
Comment (Gero1999) [inline inst/shiny/modules/tab_nca/setup.R:121]: suggestion: add something to improve the identification of the file

```suggestion
      filename = paste0("aNCA_settings_", Sys.Date(), ".rds"), 
```

**Review by Gero1999 — APPROVED** [review]
Hey LGTM and I can see now the button, thanks! Yes I agree, aesthetics will be changed soon, so as long as the UI functionalities can still remain testable for review it does not matter how good they "look". 

Everything works, so I will approve. I only added some comments that could be worthy to consider!

File: inst/shiny/modules/tab_nca/setup/settings.R [hunk 3]
```diff
@@ -0,0 +1,489 @@
...
+        not_compatible <- append(not_compatible, "Analyte")
+      }
+
+      if (all(settings$doseno %in% unique(data()$DOSNO))) {
+        updateSelectInput(inputId = "select_doseno", selected = settings$doseno)
+      } else {
+        not_compatible <- append(not_compatible, "Dose Number")
+      }
+
+      if (all(settings$pscpec %in% unique(data()$PCSPEC))) {
```
Comment (rabiibouhestine) [inline inst/shiny/modules/tab_nca/setup/settings.R:152]: is there a typo here in `pscpec` or `PCSPEC` ? they are written differently from each other.

File: inst/shiny/modules/tab_nca/setup/settings.R [hunk 4]
```diff
@@ -0,0 +1,489 @@
...
+    observeEvent(list(input$adj.r.squared_rule, input$aucpext.obs_rule,
+                      input$aucpext.pred_rule, nca_params()), {
+
+                   nca_params <- nca_params()
+                   if (input$adj.r.squared_rule) nca_params <- c(nca_params, "adj.r.squared")
+                   if (input$aucpext.obs_rule) nca_params <- c(nca_params, "aucpext.obs")
+                   if (input$aucpext.pred_rule) nca_params <- c(nca_params, "aucpext.pred")
+
+                   updatePickerInput(session = session,
+                                     inputId = "nca_params",
```
Comment (rabiibouhestine) [inline inst/shiny/modules/tab_nca/setup/settings.R:373]: There's no input with inputId = "nca_params" in the UI.

**Review by rabiibouhestine — CHANGES_REQUESTED** [review]
Great job! pleas look at my comments :)
