### PR TITLE
Bug: NCA results download not working

### LINKED ISSUE #325: Bug: NCA results download not working
### Description
NCA results download not working: 'site not available'

### To reproduce
Try to download nca results

### Expected behaviour
.CSV download should work.

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #325 

## Description

NCA results not downloading, because the name of the object was not updated with the latest changes. I have also refactored to ensure that the results match the filters put in by the user.

## Definition of Done

- [x] NCA results download works

## How to test
Create results then try to download .csv.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] Package version is incremented

### CODE REVIEW

File: inst/shiny/modules/tab_nca/nca_results.R [hunk 1]
```diff
@@ -132,15 +132,19 @@ nca_results_server <- function(id, pknca_data, res_nca, rules, grouping_vars, au
                                str_remove(col_names, "\\[.*"),
                                col_names)
 
-      final_results <- final_results() %>%
-        select(all_of(col_names[!(col_base_names %in% params_rem_cols)]))
+      final_results() %>%
+        select(c(all_of(col_names[!(col_base_names %in% params_rem_cols)])), -conc_groups)
+    })
+
+    output$myresults <- reactable::renderReactable({
```
Comment (m-kolomanski) [inline inst/shiny/modules/tab_nca/nca_results.R:139]: nitpick: while we are touching this line, we might remove the namespacing - it is not needed.
```suggestion
    output$myresults <- renderReactable({
```

**Review by m-kolomanski — APPROVED** [review]
LGTM!

**Review by Gero1999 — APPROVED** [review]
good solution, thanks!
