### PR TITLE
Bug fix: functions not available for pak installation

### LINKED ISSUE #879: Bug: functions not available for PAK installation
### Description
Attempted fix in #863, but there are more functions that don't work via pak installation.

### To reproduce
Try to install via pak, you should get errors

### Expected behaviour
Pak installation should work correctly, the same as devtools.

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #879 

## Description

Exporting functions (and adding tests where necessary) to ensure that `pak ` installation is working.

## Definition of Done

- [x] Pak installation works well

## How to test

In a clear session and envrionment, run ` pak::pak("pharmaverse/aNCA@879-bug-functions-not-available-for-pak-installation")` and then `anca::run_app()` and check that the app loads as expected.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] App or package changes are reflected in NEWS
- [x] Package version is incremented

## Notes to reviewer

Blocked by #863

### CODE REVIEW

**Review by jitendar-reddy — APPROVED** [review]

File: tests/testthat/test-label_operators.R [hunk 1]
```diff
@@ -94,3 +94,79 @@ describe("generate_tooltip_text", {
...
+    names(df_input) <- names(expected_labels_map)
+
+    df_result <- add_label_attribute(df_input, myres_base)
+
+    for (col_name in names(expected_labels_map)) {
+      expect_equal(
+        attr(df_result[[col_name]], "label"),
+        expected_labels_map[[col_name]],
+        info = paste("Checking label for", col_name)
+      )
```
Comment (m-kolomanski) [inline tests/testthat/test-label_operators.R]: nitpick: consider using `purrr::iwalk()`

**Review by m-kolomanski — APPROVED** [review]
LGTM
