### PR TITLE
Enhancement: add error warning and filtering for duplicates

### LINKED ISSUE #219: Enhancement: add error warning for duplicates in data
### Description
Currently, if the user uploads data that contains any duplicated rows (for TIME, USUBJID, ANALYTE, PCSPEC, DRUG), the app crashes. While it is expected that the app won't work if there are these duplicates, it would be better if instead of crashing, the app gave a warning message and displayed the rows that are duplicated. We also then want the user to be able to select the rows that they want to keep/remove, and filter the data accordingly.

For reporting purposes, it would be best to then keep a record of the samples that were filtered.

error message:` Rows that are not unique per group and time (column names: TIME, STUDYID, PCSPEC, DRUG, USUBJID, ANALYTE) found within concentration data.  Row numbers: x, y, z`

To recreate:
simple_data <- data.frame(
  STUDYID = rep("STUDY001", 6),
  PCSPEC = rep("Plasma", 6),
  ROUTE = rep("IV", 6),
  DRUG = rep("DrugA", 6),
  USUBJID = rep("SUBJ001", 6),
  DOSNO = rep(1, 6),
  ANALYTE = rep("AnalyteA", 6),
  AVAL = c(0, 5, 10, 7, 3, 1),
  AVALU = rep("ng/mL", 6),
  DOSEA = rep(100, 6),
  DOSEU = rep("mg", 6),
  AFRLT = c(0, 1, 2, 2, 4, 6),
  ARRLT = c(0, 1, 2, 3, 4, 6),
  NFRLT = c(0, 1, 2, 3, 4, 6),
  ADOSEDUR = rep(0.5, 6),
  RRLTU = rep("hour", 6)
)

create PKNCAdata object with above data. (in branch from #272)

### Definition of Done
The requirements for the feature to be complete:
- [ ] Error message pop up with table of duplicated rows
- [ ] Option to filter duplicated rows
- [ ] Export of table containing filtered data points.

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #219 

## Description

If there are duplicates in the data, the current error warning was too vague and not useful for the user. Now, there are a few steps involved:

1. Check for duplicates where concentration and time is duplicated. These are filtered out automatically, as their removal will not impact the results. The user is given a warning message.
2.  Check for duplicates that are flagged in PKNCAdata object creation. These are then shown in a pop up modal table.
3. The user can either (a) Cancel, and clean the data themselves, or (b) select the samples that they want to keep, and continue with these samples labelled as "DFLAG" and filtered from the PKNCAdata object.

There is a third type of duplicate- duplicates in Dosing data, however I have opted not to do anything with these as they suggest more complex issues in the data that are better dealt with outside of the app. Feel free to make suggestions if you think there is a better choice

## Definition of Done

- [x] Duplicates do not crash the app
- [x] Duplicates are filtered out if conc is the same
- [x] user can select which duplicates to keep

## How to test
Ive modified the DummyADNCA_RO dataset to contain one of each type of duplicate. You can see the interface.

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented
- [x] Package version is incremented

## Notes to reviewer
Do i need to create tests for the `apply_column_mapping` function? Not sure since its in functions folder not R folder.

### CODE REVIEW

File: R/PKNCA.R [hunk 1]
```diff
@@ -66,6 +66,13 @@ PKNCA_create_data_object <- function(adnca_data) { # nolint: object_name_linter
   matrix_column <- "PCSPEC"
   std_route_column <- "std_route"
 
+  #Filter out flagged duplicates if DFLAG column available
+  if ("DFLAG" %in% colnames(adnca_data)) {
+    adnca_data <- adnca_data %>%
+      filter(DFLAG == FALSE) %>%
```
Comment (m-kolomanski) [inline R/PKNCA.R:72]: nitpick:
```suggestion
      filter(!DFLAG) %>%
```

File: inst/shiny/functions/data_mapping_helpers.R [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+  }, simplify = FALSE)
+
+  # Log the mapping for debugging
+  mapping_log <- lapply(selected_cols, function(group) {
+    purrr::imap(group, function(v, n) paste0("* ", n, " -> ", paste0(v, collapse = ", "))
+    )
+  }) %>%
+    unlist() %>%
+    paste0(collapse = "\n")
+  log_info(paste0("The following mapping was applied:\n", mapping_log))
```
Comment (m-kolomanski) [inline inst/shiny/functions/data_mapping_helpers.R:20]: nitpick: Seems more like a `debug` kind of log, since the user can see the mapping in the UI.

I think I did this originally, sorry, my mistake.

File: inst/shiny/functions/data_mapping_helpers.R [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+      type = "error",
+      duration = 5
+    )
+    return()
+  }
+
+  # Remove "Grouping_Variables" from the "Group Identifiers" mapping
+  selected_cols[["Group Identifiers"]] <- selected_cols[["Group Identifiers"]][
+    names(selected_cols[["Group Identifiers"]]) != "Grouping_Variables"
+  ]
```
Comment (m-kolomanski) [inline inst/shiny/functions/data_mapping_helpers.R:46]: suggestion:
```suggestion
  selected_cols[["Group Identifiers"]][["Grouping_Variables"]] <- NULL
```

File: inst/shiny/functions/data_mapping_helpers.R [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+  if (input$select_DOSEU %in% manual_units$dose) {
+    dataset$DOSEU <- input$select_DOSEU
+  }
+  if (input$select_RRLTU %in% manual_units$time) {
+    dataset$RRLTU <- input$select_RRLTU
+  }
+
+  # Reorder columns per the desired order and apply labels
+  dataset <- dataset %>% relocate(all_of(MAPPING_DESIRED_ORDER))
+  dataset <- apply_labels(dataset, LABELS, "ADPC")
```
Comment (m-kolomanski) [inline inst/shiny/functions/data_mapping_helpers.R:76]: nitpick: Why split the pipe?
```suggestion
  dataset <- dataset %>%
    relocate(all_of(MAPPING_DESIRED_ORDER)) %>%
    apply_labels(LABELS, "ADPC")
```

File: inst/shiny/functions/data_mapping_helpers.R [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+    log_warn("Duplicate concentration data detected and filtered.")
+    showNotification(
+      ui = "Duplicate concentration data detected and removed. Please check the data",
+      type = "warning",
+      duration = 5
+    )
+  }
+
+  dataset <- dataset %>% anti_join(conc_duplicates, by = colnames(conc_duplicates))
+  dataset
```
Comment (m-kolomanski) [inline inst/shiny/functions/data_mapping_helpers.R:96]: nitpick:
```suggestion
  anti_join(dataset, conc_duplicates, by = colnames(conc_duplicates))
```

File: inst/shiny/modules/tab_data/data_mapping.R [hunk 6]
```diff
@@ -197,94 +203,123 @@ data_mapping_server <- function(id, adnca_data) {
...
+          ")),
+            p("The following rows are duplicates based on TIME, STUDYID,
+              PCSPEC, DRUG, USUBJID, PARAM."),
+            p("Please select the rows you would like to KEEP.
+              Rows not selected will be flagged and filtered."),
+            p("Alternatively, click 'Cancel' to discard the changes,
+              and clean the dataset yourself."),
+            div(
+              style = "overflow-x: auto; white-space: nowrap; border:
+              1px solid #ddd; padding: 1em;",
```
[the remark this answers is not in the document]
Comment (js3110) [reply inst/shiny/modules/tab_data/data_mapping.R:249]: same as above

File: inst/shiny/modules/tab_data/data_mapping.R [hunk 7]
```diff
@@ -197,94 +203,123 @@ data_mapping_server <- function(id, adnca_data) {
...
     # Observe submit button click and update processed_data
-    processed_data <- reactive({
+    mapped_data <- reactive({
       req(adnca_data())
+
       log_info("Processing data mapping...")
-      Sys.sleep(1) # Make this artificially slow to show the loading spinner
 
       dataset <- adnca_data()
+      apply_column_mapping(dataset, input, MANUAL_UNITS)
```
[the remark this answers is not in the document]
Comment (js3110) [reply inst/shiny/modules/tab_data/data_mapping.R]: hi @m-kolomanski , I'm not sure I understand. Could you expand a bit more on what I should do? thanks :)

**Comment by m-kolomanski** [comment]
@js3110 I have pushed the changes with CSS migrated to `style.css`.

File: inst/shiny/modules/tab_data/data_mapping.R (hunk 7 above)
[the remark this answers is not in the document]
Comment (m-kolomanski) [reply inst/shiny/modules/tab_data/data_mapping.R]: Hey, sorry, I have not noticed this comment before, but I see in the code that you have it figured out! :)

File: inst/shiny/functions/apply_column_mapping.R [hunk 8]
```diff
@@ -0,0 +1,93 @@
...
+  }) %>%
+    unlist() %>%
+    paste0(collapse = "\n")
+  log_debug(paste0("The following mapping was applied:\n", mapping_log))
+
+  if (any(unlist(selected_cols) == "")) {
+    log_error("Unmapped columns detected.")
+    showNotification("Some required columns are not mapped.
+                     Please complete all selections.", type = "error", duration = 5)
+    return()
```
Comment (m-kolomanski) [inline inst/shiny/functions/apply_column_mapping.R:46]: nitpick, suggestion: Since this is a _function_, it should return _some_ value - I would state it explicitly, but this is personal, stylistic preference, not something that makes any real difference
```suggestion
    return(NULL)
```

File: inst/shiny/functions/apply_column_mapping.R [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+  }
+
+  if (any(duplicated(unlist(selected_cols)))) {
+    log_error("Duplicate column selection detected.")
+    showNotification("Duplicate column selection detected.
+                     Please ensure each selection is unique.", type = "error", duration = 5)
+    return()
```
Comment (m-kolomanski) [inline inst/shiny/functions/apply_column_mapping.R:53]: nitpick: Same as before
```suggestion
    return(NULL)
```

**Review by m-kolomanski — APPROVED** [review]
Looks great to me, thank you for all the work 💪

**Review by Gero1999 — APPROVED** [review]
lgtm!
